cluster.name: docker-elasticsearch
#path.data: /var/lib/elasticsearch

bootstrap.mlockall: true
node:
    name: ${HOSTNAME}
http.cors.enabled: true
#http.cors.allow-orgin: "/.*/"
network.host: ${HOSTNAME}
