elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
  volumes:
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./elasticsearch/data:/usr/share/elasticsearch/data
#  restart: always
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/patterns:/etc/logstash/patterns_extra
    - /var/log:/mainhostlog
  links:
    - elasticsearch
#  ports:
#    - "5000:5000"
#  restart: always
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  links:
    - elasticsearch
#  ports:
#    - "5601:5601"
#  restart: always
nginx:
  build: nginx
  ports: 
      - "5443:443"
  links:
      - kibana
#  restart: always
